# Generated by Django 5.2.4 on 2025-07-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='participants', to='submissions.competition'),
        ),
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.competition'),
            preserve_default=False,
        ),
    ]
