# Generated by Django 5.1.6 on 2025-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_competition_participant_competitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=50),
        ),
    ]
