# Generated by Django 5.1.6 on 2025-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
