# Generated by Django 5.2.4 on 2025-07-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        ('submissions', '0002_competition_participant_competitions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='judge',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='judges', to='submissions.competition'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='submissions.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='competition',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='submissions.competition'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('competition', 'submission', 'judge', 'rubric')},
        ),
    ]
