# Generated by Django 5.1.6 on 2025-07-22 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_score_evaluation_file_score_evaluation_link'),
        ('submissions', '0004_submission_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('competitions', models.ManyToManyField(related_name='rubric_versions', to='submissions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scoring.rubricversion')),
            ],
        ),
    ]
